#!/usr/bin/env bash

CURL_OPTION="-v"

set -e
exec 3>&1
exec 1>&2
#set -x

function evaluate {
  __var=$1
  # escape ( and ) from markdown
  __var="${__var//\(/\\(}"
  __var="${__var//\)/\\)}"
  __var="${__var//\:/\\:}"
  __var=`eval echo $__var`
  echo $__var
}

payload=$(mktemp /tmp/resource-in.XXXXXX)
cat > "${payload}" <&0

format="markdown"
color="$(jq -r '.params.color // "00EA43"' < "${payload}")"

actionName=$(evaluate "$(jq -r '.params.actionName // "Open Concourse"' < "${payload}")")

actionTarget=$(evaluate "$(jq -r '.params.actionTarget // "https://concourse.ci"' < "${payload}")")

title=$(evaluate "$(jq -r '.params.title // "Concourse CI"' < "${payload}")")

text=$(evaluate "$(jq -r '.params.text // ""' < "${payload}")")
text_file=$(evaluate "$(jq -r '.params.text_file // ""' < "${payload}")")

# - 'text' always overrides 'text_file'
# - '_(NO MSG)_' being the default if neither are provded
# - If text file is missing: _(NO MSG FILE)_
# - If text file is blank: _(EMPTY MSG FILE)_"
text_output="_(NO MSG)_"
if [[ -n "${text_file}" ]]; then
  if [[ ! -f "${text_file}" ]]; then
    text_output="_(NO MSG FILE)_"
  else
    text_output="$(cat "${text_file}")" && \
              [[ -z "${text_output}" ]] && \
			  text_output="_(EMPTY MSG FILE)_"
  fi
fi
[[ -n "${text}" ]] && text_output="${text}"

body="{\"TextFormat\": \"${format}\", \"text\": \"${text_output}\", \"title\": \"${title}\", \"themeColor\": \"${color}\", \"potentialAction\": [{\"@context\": \"https://schema.org\", \"@type\": \"ViewAction\", \"name\": \"${actionName}\", \"target\": [\"${actionTarget}\"]}]}"

webhook_url="$(jq -r '.source.url' < "${payload}")"
redacted_webhook_url=$(echo "${webhook_url}" | sed -e 's#/\([^/\.]\{2\}\)[^/.]\{5,\}\([^/.]\{2\}\)#/\1…\2#g' | jq -R .)

url_path="$(echo ${webhook_url} | sed -e "s/https\{0,1\}:\/\/[^\/]*\(\/[^?&#]*\).*/\1/")"
curl ${CURL_OPTION} -d "${body}" "${webhook_url}" 2>&1 | sed -e "s#${url_path}#***WEBHOOK URL REDACTED***#g"

timestamp=$(date +%s)
metadata="$(cat <<EOF
{
  "version": {"timestamp": "${timestamp}"},
  "metadata": [
    {"name": "url", "value": ${redacted_webhook_url}},
    {"name": "BUILD_PIPELINE_NAME", "value": "${BUILD_PIPELINE_NAME}"}
  ]
}
EOF
)"

echo "$metadata"  >&3

